### ISSUE TITLE
bigtiff memmap 

### ISSUE THREAD

**Issue by Mirindi95** [yapic/yapic_io#20]
Hello, 
I'm doing image segmentation for plant drone data. For that purpose I used the yapic implementation. I encountered a problem within the yapic_io tiffconnector.py. Unfortunately, while mapping the predicted tiles into the prediction tiffs information gets lost, leading to cropped output files. This is, however, also the case for the example data set und not only specific for my data. The results then look like this.
![grafik](https://user-images.githubusercontent.com/45970359/114869043-d8d0a480-9df6-11eb-8350-941269e22f46.png)

Interestingly this issue occurs not on every input data. 
After some search I found the problem within the bigtiff memory mapping module. Here, the tiles are mapped into cache correctly but only the last tile is written into the output image while the rest is lost. The output image still has the desired shape. 

Best

**Comment by cmohl2013** [comment]
Thank you for reporting @Mirindi95. I have never encountered this problem so far. Would be interesting to know which operating system you use.

**Comment by cmohl2013** [comment]
Problem is solved with PR https://github.com/yapic/yapic_io/pull/22 and https://github.com/yapic/yapic_io/pull/24

Install yapic_io version >=0.2.1 to fix this issue
