### ISSUE TITLE
set default batch size

### ISSUE THREAD

**Issue by pranjaldhole** [yapic/yapic_io#37]
The line
https://github.com/yapic/yapic_io/blob/5e37ba47ece6215b911c2ab62c63bcd154781b37/yapic_io/training_batch.py#L108
raises an error for prediction if the batch size is not predefined while using the `napari-yapic-prediction` plugin.

This should be handled by setting a default batch size if not assigned.

**Comment by cmohl2013** [comment]
@pranjaldhole Defining a default batch size is an good idea. I propose to set the number of classes as default batch size for the training_batch class. The random sampling in training takes care that all labels are present in a minibatch if we have at least as many batches as classes.

For the prediction_batch class, the default batch size could be 1 to save memory. Prediction is often applied on client computers (in contrast to GPU servers for training) and are likely to have less memory available.

**Comment by pranjaldhole** [comment]
Thanks, @cmohl2013! I'll implement this for yapic.

**Comment by pranjaldhole** [comment]
https://github.com/yapic/yapic/pull/53 resolves #37
